import { _ } from '../helper.js'

export default {
  shareText: _('推荐一个开源的 OpenClaw 管理面板 — ClawPanel，一键搭建、便捷管理模型和 Agent，还内置 AI 助手帮你排查问题，小白也能轻松上手：https://claw.qt.cool', 'Recommend an open-source OpenClaw management panel — ClawPanel. It helps you set up quickly, manage models and Agents easily, and even includes an AI assistant for troubleshooting: https://claw.qt.cool', '推薦一個開源的 OpenClaw 管理面板 — ClawPanel，一鍵搭建、便捷管理模型和 Agent，還內建 AI 助手幫你排查問題，小白也能輕鬆上手：https://claw.qt.cool', 'OpenClaw を管理しやすいオープンソースの管理パネル「ClawPanel」をおすすめします。すばやくセットアップでき、モデルや Agent の管理も簡単で、トラブル対応用の AI アシスタントも内蔵しています: https://claw.qt.cool', '오픈소스 OpenClaw 관리 패널 ClawPanel을 추천합니다. 빠른 구축, 모델과 Agent의 편리한 관리, 그리고 문제 해결용 AI 도우미까지 제공합니다: https://claw.qt.cool', 'Giới thiệu một bảng điều khiển mã nguồn mở cho OpenClaw — ClawPanel. Thiết lập nhanh, quản lý model và Agent thuận tiện, còn có cả trợ lý AI hỗ trợ xử lý sự cố: https://claw.qt.cool', 'Te recomiendo un panel de administración open source para OpenClaw: ClawPanel. Permite desplegar rápido, gestionar modelos y Agents fácilmente e incluye un asistente de IA para resolver problemas: https://claw.qt.cool', 'Recomendo um painel de gerenciamento open source para OpenClaw — ClawPanel. Ele facilita a configuração, o gerenciamento de modelos e Agents, e ainda inclui um assistente de IA para troubleshooting: https://claw.qt.cool', 'Рекомендую open-source панель управления для OpenClaw — ClawPanel. Она помогает быстро развернуть систему, удобно управлять моделями и агентами, а также включает ИИ-помощника для диагностики: https://claw.qt.cool', 'Je recommande un panneau de gestion open source pour OpenClaw : ClawPanel. Il permet une mise en place rapide, une gestion simple des modèles et des Agents, et intègre un assistant IA pour le dépannage : https://claw.qt.cool', 'Ich empfehle ClawPanel, ein Open-Source-Verwaltungs-Panel für OpenClaw. Damit lässt sich schnell starten, Modelle und Agents bequem verwalten, und ein KI-Assistent hilft bei Problemen: https://claw.qt.cool'),
  title: _('感谢你使用 ClawPanel', 'Thanks for using ClawPanel', '感謝你使用 ClawPanel', 'ClawPanel を使っていただきありがとうございます', 'ClawPanel을 사용해 주셔서 감사합니다', 'Cảm ơn bạn đã sử dụng ClawPanel', 'Gracias por usar ClawPanel', 'Obrigado por usar o ClawPanel', 'Спасибо, что используете ClawPanel', 'Merci d’utiliser ClawPanel', 'Danke, dass du ClawPanel nutzt'),
  message: _('ClawPanel 是一个<strong>完全开源、免费</strong>的项目，由晴辰云团队专职维护、持续更新。如果它帮到了你，对我们最大的鼓励就是：', 'ClawPanel is a <strong>fully open-source and free</strong> project, maintained full-time and continuously improved by the QingchenCloud team. If it helped you, the best encouragement for us is:', 'ClawPanel 是一個<strong>完全開源、免費</strong>的專案，由晴辰雲團隊專職維護、持續更新。如果它幫到了你，對我們最大的鼓勵就是：', 'ClawPanel は<strong>完全オープンソースで無料</strong>のプロジェクトで、QingchenCloud チームが継続的に保守・更新しています。もし役に立ったなら、私たちにとって一番の励みは次のような応援です：', 'ClawPanel은 <strong>완전한 오픈소스이자 무료</strong> 프로젝트이며, QingchenCloud 팀이 전담 유지보수와 지속적인 업데이트를 진행하고 있습니다. 도움이 되었다면 가장 큰 응원은 다음과 같습니다:', 'ClawPanel là một dự án <strong>mã nguồn mở hoàn toàn và miễn phí</strong>, được đội ngũ QingchenCloud duy trì chuyên trách và cập nhật liên tục. Nếu nó giúp ích cho bạn, sự ủng hộ lớn nhất dành cho chúng tôi là:', 'ClawPanel es un proyecto <strong>totalmente open source y gratuito</strong>, mantenido y actualizado continuamente por el equipo de QingchenCloud. Si te ha ayudado, la mejor forma de apoyarnos es:', 'ClawPanel é um projeto <strong>totalmente open source e gratuito</strong>, mantido em tempo integral e atualizado continuamente pela equipe QingchenCloud. Se ele te ajudou, o maior incentivo para nós é:', 'ClawPanel — это <strong>полностью open-source и бесплатный</strong> проект, который команда QingchenCloud поддерживает и постоянно развивает. Если он вам помог, лучшая поддержка для нас — это:', 'ClawPanel est un projet <strong>entièrement open source et gratuit</strong>, maintenu à plein temps et continuellement amélioré par l’équipe QingchenCloud. S’il vous a aidé, le meilleur encouragement pour nous est :', 'ClawPanel ist ein <strong>vollständig quelloffenes und kostenloses</strong> Projekt, das vom QingchenCloud-Team kontinuierlich gepflegt und weiterentwickelt wird. Wenn es dir geholfen hat, ist die größte Unterstützung für uns:'),
  starTitle: _('GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star', 'GitHub Star'),
  starDesc: _('点个 Star 是最直接的支持', 'Giving us a Star is the most direct support', '點個 Star 是最直接的支持', 'Star を付けてもらえるのが一番直接的な応援です', 'Star를 눌러 주는 것이 가장 직접적인 응원입니다', 'Tặng một Star là cách ủng hộ trực tiếp nhất', 'Dar una Star es la forma más directa de apoyarnos', 'Dar uma Star é a forma mais direta de apoiar', 'Поставить Star — самый прямой способ поддержки', 'Mettre une Star est le soutien le plus direct', 'Ein Star ist die direkteste Unterstützung'),
  shareTitle: _('分享给朋友', 'Share with friends', '分享給朋友', '友だちに共有', '친구에게 공유', 'Chia sẻ với bạn bè', 'Compartir con amigos', 'Compartilhar com amigos', 'Поделиться с друзьями', 'Partager avec des amis', 'Mit Freunden teilen'),
  shareDesc: _('复制推荐文案，让更多人知道', 'Copy the recommendation text to spread the word', '複製推薦文案，讓更多人知道', '紹介文をコピーして、もっと多くの人に広めましょう', '추천 문구를 복사해 더 많은 사람에게 알려 주세요', 'Sao chép lời giới thiệu để nhiều người biết hơn', 'Copia el texto de recomendación para que más gente lo conozca', 'Copie o texto de recomendação para divulgar para mais pessoas', 'Скопируйте текст рекомендации, чтобы рассказать другим', 'Copiez le texte de recommandation pour le partager autour de vous', 'Kopiere den Empfehlungstext, damit mehr Leute davon erfahren'),
  shareCopied: _('✅ 已复制，去分享吧！', '✅ Copied, go share it!', '✅ 已複製，去分享吧！', '✅ コピーしました。ぜひ共有してください！', '✅ 복사되었습니다. 이제 공유해 보세요!', '✅ Đã sao chép, hãy chia sẻ ngay!', '✅ ¡Copiado! ¡Ahora compártelo!', '✅ Copiado! Agora compartilhe!', '✅ Скопировано, поделитесь этим!', '✅ Copié, allez le partager !', '✅ Kopiert, jetzt teile es!'),
  communityLabel: _('扫码加入社区交流群，第一时间获取更新和帮助', 'Scan to join the community groups for updates and help', '掃碼加入社群交流群，第一時間獲取更新和幫助', 'QR をスキャンしてコミュニティに参加し、最新情報やサポートを受け取りましょう', 'QR 코드를 스캔해 커뮤니티 그룹에 참여하고 업데이트와 도움을 받아보세요', 'Quét mã để tham gia cộng đồng, nhận cập nhật và hỗ trợ sớm nhất', 'Escanea para unirte a la comunidad y recibir novedades y ayuda', 'Escaneie para entrar na comunidade e receber atualizações e ajuda', 'Сканируйте код, чтобы присоединиться к сообществу и получать новости и помощь', 'Scannez pour rejoindre la communauté et recevoir des mises à jour et de l’aide', 'Scanne den Code, um der Community beizutreten und Updates sowie Hilfe zu erhalten'),
  qqAlt: _('QQ 交流群', 'QQ community group', 'QQ 交流群', 'QQ コミュニティグループ', 'QQ 커뮤니티 그룹', 'Nhóm cộng đồng QQ', 'Grupo de comunidad QQ', 'Grupo da comunidade QQ', 'Сообщество QQ', 'Groupe communautaire QQ', 'QQ-Community-Gruppe'),
  qqLabel: _('QQ 群', 'QQ Group', 'QQ 群', 'QQ グループ', 'QQ 그룹', 'Nhóm QQ', 'Grupo de QQ', 'Grupo QQ', 'Группа QQ', 'Groupe QQ', 'QQ-Gruppe'),
  wechatAlt: _('微信交流群', 'WeChat community group', '微信交流群', 'WeChat コミュニティグループ', '위챗 커뮤니티 그룹', 'Nhóm cộng đồng WeChat', 'Grupo de comunidad WeChat', 'Grupo da comunidade WeChat', 'Сообщество WeChat', 'Groupe communautaire WeChat', 'WeChat-Community-Gruppe'),
  wechatLabel: _('微信群', 'WeChat Group', '微信群', 'WeChat グループ', '위챗 그룹', 'Nhóm WeChat', 'Grupo de WeChat', 'Grupo WeChat', 'Группа WeChat', 'Groupe WeChat', 'WeChat-Gruppe'),
  douyinAlt: _('抖音交流群', 'Douyin community group', '抖音交流群', 'Douyin コミュニティグループ', '도우인 커뮤니티 그룹', 'Nhóm cộng đồng Douyin', 'Grupo de comunidad Douyin', 'Grupo da comunidade Douyin', 'Сообщество Douyin', 'Groupe communautaire Douyin', 'Douyin-Community-Gruppe'),
  douyinLabel: _('抖音群', 'Douyin Group', '抖音群', 'Douyin グループ', '도우인 그룹', 'Nhóm Douyin', 'Grupo de Douyin', 'Grupo Douyin', 'Группа Douyin', 'Groupe Douyin', 'Douyin-Gruppe'),
  feishuAlt: _('飞书交流群', 'Feishu community group', '飛書交流群', 'Feishu コミュニティグループ', '피슈 커뮤니티 그룹', 'Nhóm cộng đồng Feishu', 'Grupo de comunidad Feishu', 'Grupo da comunidade Feishu', 'Сообщество Feishu', 'Groupe communautaire Feishu', 'Feishu-Community-Gruppe'),
  feishuLabel: _('飞书群', 'Feishu Group', '飛書群', 'Feishu グループ', '피슈 그룹', 'Nhóm Feishu', 'Grupo de Feishu', 'Grupo Feishu', 'Группа Feishu', 'Groupe Feishu', 'Feishu-Gruppe'),
  dismissToday: _('今日不再弹窗', 'Do not show again today', '今日不再彈窗', '今日はもう表示しない', '오늘은 다시 보지 않기', 'Hôm nay không hiển thị lại', 'No volver a mostrar hoy', 'Não mostrar novamente hoje', 'Не показывать снова сегодня', 'Ne plus afficher aujourd’hui', 'Heute nicht mehr anzeigen'),
}
